### ISSUE TITLE
sourcemaps off by one line?

### ISSUE THREAD

**Issue by ianstormtaylor** [duojs/duo#125]
Seems like when enabling source maps the Dev Tools debugger always stops on break points one line after the actual line you highlight. Basically it's just a visual thing with the sourcemap showing that the debugger is paused on the following line, even though in reality it's on the current one o_O

**Comment by johntron** [comment]
This still wasn't working (see comments in duojs/pack#24), but duojs/pack#33 fixes this.

**Comment by johntron** [comment]
I think we just need to bump the duo-pack dependency to 1.0.11 to close this issue.
