### ISSUE TITLE
custom commands error on node 0.10

### ISSUE THREAD

**Issue by stephenmathieson** [duojs/duo#129]
since we've added node 0.10 support to duo(1), i'd expect sub-commands to work the same way.  we currently pass `--harmony-generators` to node(1) when invoking subcommands, which confuses node 0.10.

a quick fix would be to spawn `gnode` rather than `node` and remove `--harmony-generators` as gnode handles it for us.
## 
## example:

duo-foo

``` js
#!/usr/bin/env node
console.log('some duo foo')
```

yields:

``` sh
$ duo foo
Error: unrecognized flag --harmony-generators
Try --help for options
some duo foo
```

on

``` sh
$ node --version
v0.10.29
```

**Comment by Mouvedia** [comment]
@stephenmathieson is there a regression?

duo 13.2
node 0.10.33

I have this error:
```
Error: unrecognized flag --harmony-generators
Try --help for options

/usr/local/lib/node_modules/duo/lib/duo.js:273
Duo.prototype.getCache = unyield(function *() {
                                          ^

        error : SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
…
```

**Comment by stephenmathieson** [comment]
@Mouvedia we dropped support for node 0.10 in [version 0.11](https://github.com/duojs/duo/blob/master/History.md#0110--2015-03-29)
