### ISSUE TITLE
How will duo handle non-CSS images/assets?

### ISSUE THREAD

**Issue by dominicbarnes** [duojs/duo#171]
Suppose I'm using an `<img>` tag in a `.html` template, duo would never be made aware of such an asset. (and thus it would never be moved to `build/`) In component, this is where manifests came in handy, so I'm wondering how duo will work with such a case?

Will it just be up to the developer to have a script that copies known images to `build/` after `duo` has run? Is there any way duo could be notified of these assets? (when does duo look at manifest files?)

**Comment by freshfelicio** [comment]
Hi everyone, I just experimented with duo and wanted to share my usecase. I am writing a big Angular app where I *don't* want to bundle everything in one big file. I'm lazy-loading CSS with angular-css, so the CSS files should just be copied over to build with the same folder structure. I also use Angular's templateUrl loading, so I need to copy all templates over to build aswell. All I want to concat are the several JS files with Angular module definitions. I really like how duo works without any .json file etc, but I need a way to tell duo to copy these html and css files over to build. I also agree that it is simply weird to require() a html or css file in JS. Is there any progress on how duo is going to handle this?

**Comment by dominicbarnes** [comment]
@freshfelicio you aren't required to bundle everything into a single file with duo. Each file you pass as an "entry file" to duo will be copied to the `build/` directory. In your case, simply pass each of your CSS files to duo. (of course, anything those files `@import` will be inlined)

As for HTML files, you can pass those to the CLI as well, and they'll just be copied to the `build/` directory as well. (anything that's not JS or CSS is just copied)

Here's a trivial example of what you can do. This assumes you have multiple "pages" that have their own JS/CSS/HTML template. (this could likely apply to any other "bundling" strategy)

```sh
$ duo pages/*/index.js pages/*/index.css pages/*/template.html
```

**Comment by freshfelicio** [comment]
That's great, but I got a lot of files. I tried `duo app/**/*.*` but it doesn't work, it just spits out some empty lines to the command prompt. I really like duo, how it doesn't need any .json file and how it parses css files for fonts for example, but I just can't get it to work how I need it...

**Comment by dominicbarnes** [comment]
@freshfelicio try just `duo app`, it should recursively process any and all files in that directory. If you're still having trouble, let's create a new Github issue and iron this out.
