### ISSUE TITLE
copying onto symlink empties certain asset files

### ISSUE THREAD

**Issue by MatthewMueller** [duojs/duo#356]
definitely a big issue (less so with git), but not sure why this is happening.

```bash
duo --development *.{css,js}
duo *.{css,js}
```

**Comment by dominicbarnes** [comment]
I'm seeing this again, for symlinking only (copy works fine) duo is injecting only `false` (as plaintext) in place of the original file. I haven't been able to find the exact problem yet, but I'm using `--copy` as a workaround.

**Comment by dominicbarnes** [comment]
Ugh... copy isn't really working either. It's something that I'll need to look into more this weekend.

**Comment by MatthewMueller** [comment]
:-( ...

**Comment by dominicbarnes** [comment]
Aha! Found the trouble in `Duo#write()`, it just needed a `supported(entry.type)` check to make sure it didn't write `false` to the files. :P
