### ISSUE TITLE
duo(1): UX for adding authentication details to .netrc

### ISSUE THREAD

**Issue by matthewmueller** [duojs/duo#37]
Also provide better error handling when you don't have auth details.

**Comment by dominicbarnes** [comment]
Hey @matthewmueller I'm working on this and am almost finished.

Would you be able to move [node-netrc](https://github.com/matthewmueller/node-netrc) and give @duojs/owners access to it? (I'd like to add a save/write method to that module for this purpose)

**Comment by matthewmueller** [comment]
done!

**Comment by dominicbarnes** [comment]
NICE! I'll have a few PRs ready pretty soon. :)
