### ISSUE TITLE
EPERM error on windows when importing Bootstrap

### ISSUE THREAD

**Issue by alessioalex** [duojs/duo#422]
So I've tried using import in my css and running the build with either ones of `@import 'twbs/bootstrap@v3.3.1:dist/css/bootstrap.css'` and `@import './custom-components/bootstrap/css/bootstrap.css'`.

Each time I get this:

```
$ duo general.js general.css && serve

     building : general.js
        using : component_compat
        using : stoj
     building : general.css
        using : component_compat
        using : stoj
        built : general.js
        error : Error: EPERM, symlink 'c:\Users\avladutu\workplace\duo-version\c
ustom-components\bootstrap\fonts\glyphicons-halflings-regular.eot'
```

I'm on Windows 7 with latest Node stuff and Git Bash installed.

Any tips?

**Comment by kevva** [comment]
Are you running as an administrator?

**Comment by alessioalex** [comment]
No, I am at work and don't have admin rights.

**Comment by kevva** [comment]
Then you can't create symlinks.

**Comment by alessioalex** [comment]
So the fact is that I cannot use Duo then on Windows unless I'm an admin? Is there no workaround if symlinks aren't allowed.. ?

**Comment by kevva** [comment]
Use it with the `--copy` flag.

**Comment by topherfangio** [comment]
@kevva Thanks! Hadn't seen the `--copy`. It worked great for me :-)
