### ISSUE TITLE
Wildcard problem in windows

### ISSUE THREAD

**Issue by MrHyde** [duojs/duo#435]
Trying the basic thing from readme like
duo *.js
leads to extremely unexpected result:
![](http://i.imgur.com/1pLjVIa.png)
No debug info, no files, nothing.
Trying the same command in cygwin env:
![](http://i.imgur.com/kraz0nF.png)

This makes usage of duo on windows very problematic :(

Windows 10 x64 TP (build 9926)
node -v
v0.10.36
npm -v
2.5.1
duo -V
0.9.4

**Comment by stephenmathieson** [comment]
yeah, windows doesn't expand wildcards as expected.  imo, this is a documentation problem on our end.

fyi, you can do this instead:

```sh
$ duo admin.js main.js
```
