### ISSUE TITLE
Implement duo cache clean

### ISSUE THREAD

**Issue by darsain** [duojs/duo#437]
Duo caches resolved tags in `os.tmpdir() . '/duo'`, but doesn't provide an API to clean that when necessary.

Did some tagging shenanigans today and couldn't figure out why duo was resolving version to an old commit, as there was no mention of any caching happening in docs, nor any cleaning command to suggest something like that is in duo, so I've spend quite some time looking in another direction while debugging the issue. Damn it :)

**Comment by stephenmathieson** [comment]
thoughts on a `duo-clear-cache` command?

could be something as simple as:

```js
#!/usr/bin/env node
var rm = require('rimraf').sync
var os = require('os')
var path = require('path')

var cache = path.join(os.tmpdir(), 'duo')

rm(cache)
```

**Comment by MatthewMueller** [comment]
i'm +1, given that the caching issues still haven't been resolved.

**Comment by stephenmathieson** [comment]
cool, i'll put something together soonish

**Comment by dominicbarnes** [comment]
In case it wasn't obvious, this script should also destroy `components/duo.json`.

Also, should we follow node's convention and use `duo cache clean` ?
