### ISSUE TITLE
manifest required?

### ISSUE THREAD

**Issue by markreg** [duojs/duo#446]
Is a component.json manifest required? I was under the impression that duo can resolve dependencies automatically.

**Comment by dominicbarnes** [comment]
You don't _need_ a manifest at all to use duo. Simply adding your dependencies as `require('{owner}/{project}');` is sufficient. Additional semantics include:

 * `require('{owner}/{project}@{version}');` specify a specific branch/tag/sha to use
 * `require('{owner}/{project}:{path}');` specify an alternative to `index.js` as your module's entry point
(you can also combine these 2: `require('{owner}/{project}@{version}:{path}');`)

**Comment by markreg** [comment]
The duojs.com website seems to imply that a manifest is required for public components:
`To create your own public component, just add a component.json to your repository` Maybe that wording should be changed?

**Comment by stephenmathieson** [comment]
@markreg PRs welcome
