### ISSUE TITLE
Consider dropping the hard gnode dependency

### ISSUE THREAD

**Issue by dominicbarnes** [duojs/duo#448]
In response to #433 and #445, I think it's time to consider dropping `gnode` throughout the duo libs:

 * It's becoming more common for devs to use ES6 transpilers, and our hard coupling with gnode prevents others (like babel) from being used easily (#445)
 * Some bugs have been really tricky to pin down, (#433) but that problem would have been solved much faster if we just got a syntax error right away
 * Stack traces get really confusing when gnode is pulled in automatically
 * node 0.12 is now the official stable version, and iojs has generators enabled w/o the flag, so I don't think we need to put _as much_ effort into supporting node 0.10 (we should still support it, but we use gnode only for our CI tests)
 * We _already_ expose `_duo` as the raw node script, making it easy to support other transpilers (and even gnode if people so desire) to execute duo's CLI in a specific env

**Comment by MatthewMueller** [comment]
+1 i'm fine with this

**Comment by dominicbarnes** [comment]
I'm going to push forward on this soon, it seems like lots of weird edge-cases are cropping up because of gnode/regenerator. (and with people using node 0.12 more often, the errors mentioned here really obscure the fact that the `--harmony-generators` flag was left out)

**Comment by MatthewMueller** [comment]
sgtm!

**Comment by stephenmathieson** [comment]
+1 from me, but unfortunately, a lot of my team is still using node 0.10... and it's what we've got in production.

i'll either get people to move to iojs/node 0.12, or try to hack something together on my end using gnode.

**Comment by dominicbarnes** [comment]
@stephenmathieson yeah, my team still has node 0.10 around as well. (though we're using 0.11 more often) Thankfully, all you need to do if you know you're using node 0.10 is to add `gnode` to your build command. (you guys use make right?)

**Comment by stephenmathieson** [comment]
yep, we'll just:

```Makefile
build.js: ...
  $(BIN)/gnode $(BIN)/_duo ...
```

**Comment by dominicbarnes** [comment]
The last dependency including gnode is duo-test, but since that's a sub-command it doesn't affect duo core anymore.
