### ISSUE TITLE
Files, fonts and assets?

### ISSUE THREAD

**Issue by slifszyc** [duojs/duo#458]
Sorry but has this https://github.com/duojs/duo/issues/171 been solved in any way by Duo?

Or best solution is to have those assets copied in another way?

**Comment by dominicbarnes** [comment]
This has been resolved, you can pass arbitrary files to the duo CLI and it will copy them to the `build/` directory.

```sh
# copies everything in the public directory to build/public/
$ duo public/

# copies to build/logo.svg
$ duo logo.svg
```

**Comment by dominicbarnes** [comment]
Sorry that wasn't documented more clearly, but that feature was added back in 0.9.0

**Comment by cristiandouce** [comment]
@dominicbarnes Is there a way to handle it via the component.json so that I can be sure it copies the dependency assets?

**Comment by slifszyc** [comment]
And is this available from the [https://github.com/duojs/duo/blob/master/docs/api.md](Javascript API)?

**Comment by dominicbarnes** [comment]
@cristiandouce unfortunately, not at the moment. However, the css-compat plugin could likely be extended to cover that situation as well. (PRs welcome)

@slifszyc yeah, the CLI simply passes those arguments as entries to the JS API.

**Comment by cristiandouce** [comment]
@dominicbarnes Where should I start looking? :wink:

**Comment by cristiandouce** [comment]
Never mind, I think I've got it
