### ISSUE TITLE
Some packages have sub dependencies that make duo think its another github repository

### ISSUE THREAD

**Issue by johnruddell** [duojs/duo#459]
I just started creating a project using duo. Really loving it so far. I noticed that some repositories have sub dependencies that causes duo to think they are github repositories and fail when looking for them. I'm using React, and the [react-router](https://github.com/rackt/react-router) from Rackt. In the react-router they have requires like this:

    var invariant = require("react/lib/invariant");

which makes duo look for a github repo. 

this is the error message

    [
        Error: Command failed: /bin/sh -c git ls-remote --tags --heads https://github.com/lib/invariant
        remote: Repository not found.
        fatal: repository 'https://github.com/lib/invariant/' not found
    ]

Please let me know if you need more information about this and I'll try and provide more details, Thanks!

**Comment by schnie** [comment]
Hey @johnruddell, having the same issue.  Were you able to get around this somehow?

**Comment by dominicbarnes** [comment]
This syntax is not supported in duo, you should use the following syntax instead:

```js
var invariant = require('react:lib/invariant');
```

The `:` basically tells duo to look for that path within the `react` repo.

**Comment by schnie** [comment]
Ah, thanks!

**Comment by dominicbarnes** [comment]
I'll go ahead and close this ticket, please re-open if that doesn't solve your issue.

**Comment by johnruddell** [comment]
@dominicbarnes that doesn't solve the issue. I dropped react-router because it broke the whole system. the issue with your solution is that require is not my code. 
`var invariant = require("react/lib/invariant");` is a part of the react-router package. Duo needs to ignore node module packages when compiling
