### ISSUE TITLE
Es6 module syntax

### ISSUE THREAD

**Issue by ismay** [duojs/duo#463]
Are there plans to move towards the es6 module syntax? Just curious, since I'm trying to asses whether it'll be possible to integrate duo in the ember-cli build process.

Ember-cli uses the es6-module-transpiler, so I'm trying to retain that convention, but still integrate duo with the build process.

**Comment by dominicbarnes** [comment]
As of right now, I don't forsee us switching to ES6 syntax, but that shouldn't stop you from using duo.

You can write ES6 modules and use something like [duo-babel](https://github.com/babel/duo-babel) to transpile it. (or, the `es6-module-transpiler` could be made into a pretty small plugin) Lastly, you can use the `--standalone` option to output a UMD. (which should be consumable by AMD/ember)
