### ISSUE TITLE
Convert Duo.js module to node.js module

### ISSUE THREAD

**Issue by zooshme** [duojs/duo#465]
Hi. Is there a way I could require a javascript module compiled by duo.js into a node application on the back end?  At the moment when I require it, it is simply an empty object. I have tried installing node-amd-loader but still the same result.

**Comment by dominicbarnes** [comment]
I have no idea if this will work, but try compiling with `--standalone "module.exports"`:

```sh
$ duo --standalone "module.exports" --stdout input.js > output.js
```

**Comment by zooshme** [comment]
Thank you. It works. Is there a way to require the resulted code without writing to a file?

**Comment by dominicbarnes** [comment]
I doubt it, I'm afraid.
