### ISSUE TITLE
Error when passing empty string into .entry()

### ISSUE THREAD

**Issue by darsain** [duojs/duo#484]
So I lost an hour on this :expressionless:. When you do:

```js
new Duo(process.cwd()).entry('', 'css').run(console.log.bind(console))
```

You get:

```
Error: cannot find entry: source.css
```

Seems like you are not doing any type checking on [`this.raw`](https://github.com/duojs/duo/blob/3e4f8fe883bfcb901db92586c9f448f89f58b560/lib/file.js#L127) or [`this.src`](https://github.com/duojs/duo/blob/3e4f8fe883bfcb901db92586c9f448f89f58b560/lib/file.js#L105) throughout the code. Please use `== null`.

**Comment by dominicbarnes** [comment]
Gotcha, so if you happen to have an empty file, it freaks out?

**Comment by darsain** [comment]
Empty file, as in `.entry('./empty.css')` works properly => builds an empty result.

The error is thrown specifically in the case above: passing the **raw contents** of a file directly in 1st, and type hint in 2nd argument, so you are not touching the harddrive at all.

**Comment by dominicbarnes** [comment]
Gotcha! I'll take a look at this
