### ISSUE TITLE
Unable to install duo; failed to fetch vargs from registry

### ISSUE THREAD

**Issue by Alhadis** [duojs/duo#494]
This might be the fault of the `vargs` maintainer, but beyond what's implied by a [very absent page](https://www.npmjs.com/package/vargs) at NPM.js, I'm unable to find anything that'd explain why the dependency is suddenly breaking installs.

This was what was sent to STDERR after running `npm -g install duo`:
```
> leveldown@1.4.0 install /usr/local/lib/node_modules/duo/node_modules/duo-cache/node_modules/level/node_modules/leveldown
> prebuild --download

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "-g" "install" "duo"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3

npm ERR! failed to fetch from registry: https://registry.npmjs.org/vargs
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johngardner/Desktop/npm-debug.log
```

I've copied the [npm-debug.log](http://pastebin.com/1SYgpGBK) to PasteBin, as the result was too big to fit in a GitHub issue.

Is this a temporary issue?

## System specs
- **NPM version:** 2.13.3
- **Node.js version:** 0.12.7
- **OS:** Mac OS/X v10.9.5 (Mavericks: Yosemite and El-whatever can go to hell)
- **Hardware:** MacBook Pro (2.3 GHz Intel Core i7 / 16 GB 1600 MHz DDR3)

**Comment by dominicbarnes** [comment]
I've started seeing this on CI now, I'm not sure what's happening yet either. :\

I can't seem to reproduce locally though, which is really weird. (I'm hoping it's a transient bug, I'll report back if I discover anything)

**Comment by dominicbarnes** [comment]
I don't see this consistently, how about you @Alhadis ?

As best I can tell, it's a transient/temporary problem.

**Comment by Alhadis** [comment]
Weird. :| It appears to be working now.

It was failing repeatedly last night, I tried about three or four times between 15-minute intervals, so I was convinced it wasn't *too* temporary.

Strange... leaving this issue open to grant visibility to the matter, though, as the catalyst of the issue probably warrants identification.

**Comment by dominicbarnes** [comment]
Looks like this was an issue with the [npm registry](https://status.npmjs.org/incidents/t80fpy8qxnwq) that affected very old packages. (of which `vargs` is one of them)

**Comment by Alhadis** [comment]
Heh, fair enough. Of ALL the times I had to look at choosing a front-end package manager (after years of giving the finger to Bower, Gulp, Grunt, and other gay-sounding platforms), my decision HAD to fall within that 14-hour window. :')

Sorry about the trouble.
